#!/usr/sbin/nft -f
# /etc/nftables.conf  —  Passerelle Bordeaux (GW-BDX)
# enp0s3 = WAN | enp0s8 = LAN | enp0s9 = DMZ | tun0 = VPN site-à-site | tun1 = road-warrior
flush ruleset

table inet fw {
  chain input {
    type filter hook input priority 0; policy drop;
    ct state established,related accept
    iifname "lo" accept
    iifname "enp0s8" accept                 # administration depuis le LAN
    iifname { "tun0", "tun1" } accept        # trafic tunnelé
    udp dport { 1194, 1195 } accept          # OpenVPN entrant (WAN)
    ip protocol icmp accept
  }

  chain forward {
    type filter hook forward priority 0; policy drop;
    ct state established,related accept
    iifname { "tun0", "tun1" } accept        # depuis les tunnels
    oifname { "tun0", "tun1" } accept        # vers les tunnels
    iifname "enp0s8" oifname "enp0s3" accept # LAN -> Internet
    # Publication web : WAN -> DMZ uniquement 80/443
    iifname "enp0s3" oifname "enp0s9" tcp dport { 80, 443 } accept
    # Cloisonnement : la DMZ ne peut PAS initier vers le LAN
    iifname "enp0s9" oifname "enp0s8" drop
    # LAN -> DMZ autorisé (administration / API contrôlée)
    iifname "enp0s8" oifname "enp0s9" accept
  }

  chain output { type filter hook output priority 0; policy accept; }
}

table ip nat {
  chain prerouting {
    type nat hook prerouting priority -100; policy accept;
    # DNAT : publication du serveur web (DMZ)
    iifname "enp0s3" tcp dport { 80, 443 } dnat to 172.16.10.10
  }
  chain postrouting {
    type nat hook postrouting priority 100; policy accept;
    # NAT pour Internet, PAS pour l'inter-sites (10.0.0.0/8)
    ip saddr 10.10.0.0/24  ip daddr != 10.0.0.0/8 oifname "enp0s3" masquerade
    ip saddr 172.16.10.0/24 ip daddr != 10.0.0.0/8 oifname "enp0s3" masquerade
  }
}
