# /etc/openvpn/server/roadwarrior.conf  —  Hub Bordeaux (GW-BDX)
# 2e instance OpenVPN : accès distant des télétravailleurs
port 1195
proto udp
dev tun

ca       ca.crt
cert     bordeaux.crt
key      bordeaux.key
dh       dh.pem
tls-auth ta.key 0

topology subnet
server 10.8.0.0 255.255.255.0

# Accès aux ressources internes (LAN des 3 sites)
push "route 10.10.0.0 255.255.255.0"
push "route 10.20.0.0 255.255.255.0"
push "route 10.30.0.0 255.255.255.0"

# Résolution interne
push "dhcp-option DNS 10.10.0.10"
push "dhcp-option DOMAIN fiducis.lan"

# Split-tunnel (pas de redirect-gateway) : surf perso reste local
keepalive 10 120
persist-key
persist-tun

cipher AES-256-GCM
auth SHA256
tls-version-min 1.2
remote-cert-tls client

# Révocation
# crl-verify crl.pem

user nobody
group nogroup
status /var/log/openvpn/rw-status.log
verb 3
